require:
  - rubocop-performance

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - bin/*
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
